//! Build script.
//!
//! Runs `tauri_build::build()` as before, plus codegen for the built-in
//! adapter registry: parse `adapters.toml`, emit
//! `$OUT_DIR/registered_adapters.rs` which `src/db/builtin.rs` includes.
//!
//! This lets us add a new built-in adapter by editing `adapters.toml` +
//! adding one path-dep in `Cargo.toml`, without touching any `.rs` file.

use std::fs;
use std::path::PathBuf;

use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct AdaptersToml {
    #[serde(default)]
    adapter: Vec<AdapterEntry>,
}

#[derive(Debug, Deserialize)]
struct AdapterEntry {
    /// Folder under `adapters/` and manifest key.
    name: String,
    /// Override for the factory type name. Defaults to `<Name>Factory`
    /// (PascalCase of `name`, plus `Factory`).
    #[serde(default)]
    factory: Option<String>,
    /// When true, the factory constructor takes `Arc<dyn KnownHostsStore>`.
    /// When false, it's a zero-arg `new()`.
    #[serde(default)]
    needs_known_hosts: bool,
}

fn main() {
    tauri_build::build();

    // Load APP_TOKEN from CI env or the workspace .env file and forward it as
    // a compile-time env var. GitHub Actions will not have a local .env file,
    // so environment wins when present.
    println!("cargo:rerun-if-env-changed=APP_TOKEN");
    println!("cargo:rerun-if-changed=../.env");
    let env_path = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap())
        .parent()
        .unwrap()
        .join(".env");
    let mut app_token = std::env::var("APP_TOKEN").ok().filter(|v| !v.trim().is_empty());
    if app_token.is_none() && env_path.exists() {
        app_token = fs::read_to_string(&env_path)
            .unwrap_or_default()
            .lines()
            .map(str::trim)
            .find_map(|line| line.strip_prefix("APP_TOKEN=").map(str::to_string))
            .filter(|v| !v.trim().is_empty());
    }
    if let Some(val) = app_token {
        let val = val.trim();
        if val.len() != 64 || !val.bytes().all(|b| b.is_ascii_hexdigit()) {
            panic!("APP_TOKEN must be a 64-character hex string");
        }
        println!("cargo:rustc-env=APP_TOKEN={val}");
    }

    // Re-run whenever the enrollment list changes. Cargo will also re-run
    // on changes to `Cargo.toml` automatically.
    println!("cargo:rerun-if-changed=adapters.toml");

    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let adapters_toml = manifest_dir.join("adapters.toml");
    let cargo_toml = manifest_dir.join("Cargo.toml");
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let out_path = out_dir.join("registered_adapters.rs");

    let entries = if adapters_toml.exists() {
        let raw = fs::read_to_string(&adapters_toml)
            .unwrap_or_else(|e| panic!("read adapters.toml: {e}"));
        let parsed: AdaptersToml =
            toml::from_str(&raw).unwrap_or_else(|e| panic!("parse adapters.toml: {e}"));
        parsed.adapter
    } else {
        Vec::new()
    };

    // Drift check: every adapter enrolled here must also be a path-dep in
    // Cargo.toml. Cargo reads its own manifest at build time; `build.rs`
    // can't rewrite it safely, so we detect the mismatch and stop the build
    // with a clear message.
    let cargo_raw = fs::read_to_string(&cargo_toml).unwrap_or_default();
    for entry in &entries {
        let dep_name = format!("adapter-{}", entry.name);
        if !cargo_raw.contains(&dep_name) {
            panic!(
                "adapters.toml enrolls `{}` but `{}` is not a dependency in Cargo.toml. \
                 Add it as a path-dep (e.g. `{} = {{ path = \"../src-adapters/{}/backend\" }}`) and rebuild.",
                entry.name, dep_name, dep_name, entry.name
            );
        }
    }

    let generated = generate(&entries);
    fs::write(&out_path, generated).unwrap_or_else(|e| panic!("write generated adapters: {e}"));
}

fn generate(entries: &[AdapterEntry]) -> String {
    // One helper `register_all` so `builtin.rs` is a 3-line `include!` shell.
    // Both forms of factory construction are emitted inline — no runtime
    // dispatch, no trait objects for the constructor. Everything the
    // compiler needs to resolve each factory type is present verbatim.
    let mut body = String::new();
    body.push_str(
        "// @generated by build.rs from adapters.toml — DO NOT EDIT.\n\
         //\n\
         // Register every compile-time-known adapter with `factories`.\n\
         // Adding a new entry in `adapters.toml` regenerates this file.\n\
         pub fn register_all(\n\
         \x20   factories: &crate::db::adapter_registry::FactoryRegistry,\n\
         \x20   known_hosts: std::sync::Arc<dyn adapter_api::ssh_hosts::KnownHostsStore>,\n\
         ) {\n",
    );

    if entries.is_empty() {
        body.push_str("    let _ = (factories, known_hosts);\n");
    } else {
        // `let _ = known_hosts;` keeps the variable live when no adapter
        // consumes it, avoiding an unused-variable warning at build time.
        let any_uses_hosts = entries.iter().any(|e| e.needs_known_hosts);
        if !any_uses_hosts {
            body.push_str("    let _ = known_hosts;\n");
        }
        for entry in entries {
            let crate_ident = format!("adapter_{}", entry.name); // hyphens illegal in idents
            let factory_ident = entry
                .factory
                .clone()
                .unwrap_or_else(|| format!("{}Factory", pascal_case(&entry.name)));
            let ctor_args = if entry.needs_known_hosts {
                "known_hosts.clone()"
            } else {
                ""
            };
            body.push_str(&format!(
                "    factories.register(std::sync::Arc::new(::{crate_ident}::{factory_ident}::new({ctor_args})));\n"
            ));
        }
    }

    body.push_str("}\n");
    body
}

fn pascal_case(s: &str) -> String {
    // `name` is lowercase ascii + hyphens/underscores. Split on non-alnum
    // and capitalise each word. "mysql" → "Mysql", "sql-server" → "SqlServer".
    let mut out = String::with_capacity(s.len());
    let mut upper_next = true;
    for c in s.chars() {
        if c.is_ascii_alphanumeric() {
            if upper_next {
                out.extend(c.to_uppercase());
                upper_next = false;
            } else {
                out.push(c);
            }
        } else {
            upper_next = true;
        }
    }
    out
}
